safelist = [
    'version',
    'jobs',
    'simidxs',
    'simidxs_mf',
    'tasks',
    'cl_analysis',
    'blt_pert',
    'itmax',
    'cg_tol',
    'mfvar',
    'dlm_mod',
    'spectrum_calculator',
    'binning',
    'outdir_plot_root',
    'outdir_plot_rel',
    'OMP_NUM_THREADS',
]