language: python

dist: xenial   # required for Python >= 3.7

git:
  depth: false

matrix:
  include:
    - name: "GCC9"
      addons:
        apt:
          sources:
            - ubuntu-toolchain-r-test
          packages:
            - gfortran-9
      env:
        - GCC_VERSION="9"
        - CHANNEL="conda-forge"
      python: "3.6"

install:
  - mkdir -p gfortran-symlinks
  - ln -s /usr/bin/gfortran-$GCC_VERSION gfortran-symlinks/gfortran
  - export PATH=$PWD/gfortran-symlinks:$PATH
  - gfortran --version
  - pip install -e .